#MOST CHANGE VARIABLE
OUTPUT=output #file to compare

WEBSERV_DIR=..
WEBSERV=$WEBSERV_DIR/webserv

NGINX_IP=127.0.0.1
NGINX_PORT=80
WEBSERV_IP=127.0.0.1
WEBSERV_PORT=8080

NGINX_IMAGE=nginx_serv
PATH_TO_DOCKERFILE=./nginx_serv

SRCS_PATH=$(pwd)/srcs

SEND_REQUEST_PY=tester/send_request.py

SLEEP_TIMER=5
#END MOST CHANGE VARIABLE 

NG_DELETE_DIR=delete_dir1
WS_DELETE_DIR=delete_dir2

#VM_CONFIG
IMAGE_NAME=nginx_serv
CONTAINER_NAME=nginx_container
VM_SRCS_PATH=/srcs
VM_CONFIG_PATH_DIR=/etc/nginx/conf.d/
VM_CONFIG_PATH=${VM_CONFIG_PATH_DIR}default.conf


#FILE CONFIG
NG_DIRECTORY_CONF=$(pwd)/nginx_config
WS_DIRECTORY_CONF=$(pwd)/webserv_config

ERROR_CONF=error.conf
INDEX_OFF_CONF=index_off.conf
MULTIPLE_LOCATION_CONF=multiple_location.conf
REDIRECT_CONF=redirect.conf
SAME_ERROR_CONF=same_error.conf
PHP_ERROR_CONF=same_error_php.conf
MULTIPLE_CONF=multiple_config

NG_ERROR_CONF=$NG_DIRECTORY_CONF/$ERROR_CONF
NG_INDEX_OFF_CONF=$NG_DIRECTORY_CONF/$INDEX_OFF_CONF
NG_MULTIPLE_LOCATION_CONF=$NG_DIRECTORY_CONF/$MULTIPLE_LOCATION_CONF
NG_REDIRECT_CONF=$NG_DIRECTORY_CONF/$REDIRECT_CONF
NG_SAME_ERROR_CONF=$NG_DIRECTORY_CONF/$SAME_ERROR_CONF
NG_PHP_ERROR_CONF=$NG_DIRECTORY_CONF/$PHP_ERROR_CONF
NG_MULTIPLE_CONF=$NG_DIRECTORY_CONF/$MULTIPLE_CONF

WS_ERROR_CONF=$WS_DIRECTORY_CONF/$ERROR_CONF
WS_INDEX_OFF_CONF=$WS_DIRECTORY_CONF/$INDEX_OFF_CONF
WS_MULTIPLE_LOCATION_CONF=$WS_DIRECTORY_CONF/$MULTIPLE_LOCATION_CONF
WS_REDIRECT_CONF=$WS_DIRECTORY_CONF/$REDIRECT_CONF
WS_SAME_ERROR_CONF=$WS_DIRECTORY_CONF/$SAME_ERROR_CONF
WS_PHP_ERROR_CONF=$WS_DIRECTORY_CONF/$PHP_ERROR_CONF
WS_MULTIPLE_CONF=$WS_DIRECTORY_CONF/$MULTIPLE_CONF